# Generated by Django 5.0.7 on 2025-01-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100)),
                ('appreciation_date', models.DateField()),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appreciated_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appreciation_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('market_conditions', models.TextField()),
                ('maintenance_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('date_purchased', models.DateField()),
                ('Buying_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.CharField(max_length=100)),
                ('approved_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('needs_approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100)),
                ('depreciation_date', models.DateField()),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depreciated_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('market_conditions', models.TextField()),
                ('maintenance_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
